eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
hystrix:
  command:
    default:
        execution:
            timeout:
                enabled: false
            isolation:
              thread:
                timeoutInMilliseconds: 1